### ISSUE TITLE
[API] Surface the .NET Core SDK/runtime download progress

### ISSUE THREAD

**Issue by daniv-msft** [dotnet/vscode-dotnetcore#13]
While the .NET Core SDK/runtime is being installed, I expect VS Code extensions to display something to the users to let them know the installation is completing.

Given the size of the .NET Core binaries (25Mb for the runtime, 120Mb for the SDK), it might be great to provide a download progress, so that extensions can surface this information as well and make the user experience better.

Do you think it could make sense to include this in the API?

If in the end only the runtime is provided, then we might skip this as the size is significantly lower.

**Comment by sfoslund** [comment]
This functionality is already provided through the [dotnet.showAcquisitionLog command](https://github.com/dotnet/vscode-dotnetcore/blob/master/dotnetcore-acquisition-library/src/extension.ts#L57).
